### ISSUE TITLE
[Feature Request] Add support for NTP

### ISSUE THREAD

**Issue by nik-markovic** [FreeRTOS/iot-reference-nxp-rt1060#31]
coreSNTP and time synchronization is not a part of the project and not integrated into the system calls like gettimeofday()/time(). Our project is migrating from Amazon FreeRTOS codebase (which supports SNTP) and needs the current system time, and I suspect that other projects could benefit from this feature too. 

Also it doesn't seem that we can check for expiration of certificates when connecting to a server, because time is not available.

Thanks,
Nik

**Comment by Skptak** [comment]
Hey @nik-markovic, thanks for bringing this feature request to our attention. Since this is a very similar feature request to [this post you made](https://github.com/FreeRTOS/iot-reference-stm32u5/issues/73) I'm going to close this one. 
If you think this decision is incorrect feel free to re-open this post, or create another one, with an explanation as to why.
