### ISSUE TITLE
[Feature Request] Add support/sample for HTTP

### ISSUE THREAD

**Issue by nik-markovic** [FreeRTOS/iot-reference-nxp-rt1060#32]
It would be nice if coreHTTP was included in the project along with a reference implementation showing an example HTTPS connection being made. We need to make an HTTPS REST call before connecting to MQTT, so having a reference implementation would be very helpful.

Thanks,
Nik

**Comment by RichardBarry** [comment]
Although not integrated into this project, you will find a set of coreHTTP demos here: https://freertos.org/mqtt/basic-mqtt-example.html

**Comment by Skptak** [comment]
Hey @nik-markovic, thanks for bringing this feature request to our attention. Since this is a very similar feature request to [your post here](https://github.com/FreeRTOS/iot-reference-stm32u5/issues/72) I'm going to close this one. The other link has additional information on it, as well as more descriptive version of the problem you're facing.
If you think this decision is incorrect feel free to re-open this post, or create another one, with an explanation as to why.

**Comment by krantik** [comment]
@Skptak I understand your thought process to close the tickets with urgency, closing them without proper resolution doesn't make sense, especially at some point when this feature is implemented in this repo you need a ticket to show the changes and also there will be platform specific code for this repo.
